
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.ContentTagging.TextAnalytics.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "Sentiment Range" template.</summary>
  public partial class SentimentRange : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{84FC0D52-E2B3-4D70-8981-B951D9F4535E}");

    public SentimentRange(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID Display = ID.Parse("{2C451704-82B6-4ACD-B848-8FF5129D42EB}");

      public static readonly ID Lower = ID.Parse("{55CB2006-F574-4D8A-8DC8-F6D8302EBDC5}");

      public static readonly ID Higher = ID.Parse("{405A9AAE-A5F7-4F16-A50D-A5407D35227E}");

    }
    
    /// <summary>Gets or sets the "Display" field.</summary>
    public string Display 
    {
      get 
      {
        return this.InnerItem[FieldIds.Display];
      }
      set
      {
        this.InnerItem[FieldIds.Display] = value;
      }
    }
  
    /// <summary>Gets or sets the "Lower" field.</summary>
    public string Lower {
      get 
      {
        return this.InnerItem[FieldIds.Lower];
      }
      set 
      {
        this.InnerItem[FieldIds.Lower] = value;
      }
    }
  
    /// <summary>Gets or sets the "Higher" field.</summary>
    public string Higher {
      get 
      {
        return this.InnerItem[FieldIds.Higher];
      }
      set 
      {
        this.InnerItem[FieldIds.Higher] = value;
      }
    }
  
    public static SentimentRange Create(Item item) 
    {
      return new SentimentRange(item);
    }

    public static implicit operator Item (SentimentRange item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator SentimentRange(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
      
  /// <summary>Represents the "_Text Analytics Entity" template.</summary>
  public partial class __TextAnalyticsEntity : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{60E2F69B-28CD-4C18-8003-1035DE182F49}");

    public __TextAnalyticsEntity(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID Sentiment = ID.Parse("{A6076C21-FEB4-469C-8A98-A7FB954F4644}");

      public static readonly ID SentimentRating = ID.Parse("{CAF6F1D5-E3C3-4D03-9F27-80E6F171635D}");

      public static readonly ID Entities = ID.Parse("{36D1CC96-6DA1-4F1F-BCC9-80FEEF0638B2}");

      public static readonly ID TextAnalyticsMD5 = ID.Parse("{F0E060CA-5536-4098-A75F-250E765EA0A3}");

    }
    
    /// <summary>Gets the "Sentiment" field.</summary>
    public LookupField Sentiment 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.Sentiment];
      }
    }
  
    /// <summary>Gets or sets the "Sentiment Rating" field.</summary>
    public string SentimentRating 
    {
      get 
      {
        return this.InnerItem[FieldIds.SentimentRating];
      }
      set
      {
        this.InnerItem[FieldIds.SentimentRating] = value;
      }
    }
  
    /// <summary>Gets or sets the "Entities" field.</summary>
    public string Entities {
      get 
      {
        return this.InnerItem[FieldIds.Entities];
      }
      set 
      {
        this.InnerItem[FieldIds.Entities] = value;
      }
    }
  
    /// <summary>Gets or sets the "TextAnalytics MD5" field.</summary>
    public string TextAnalyticsMD5 
    {
      get 
      {
        return this.InnerItem[FieldIds.TextAnalyticsMD5];
      }
      set
      {
        this.InnerItem[FieldIds.TextAnalyticsMD5] = value;
      }
    }
  
    public static __TextAnalyticsEntity Create(Item item) 
    {
      return new __TextAnalyticsEntity(item);
    }

    public static implicit operator Item (__TextAnalyticsEntity item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __TextAnalyticsEntity(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
